// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CSMoveReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_6(); }
  public static CSMoveReq GetRootAsCSMoveReq(ByteBuffer _bb) { return GetRootAsCSMoveReq(_bb, new CSMoveReq()); }
  public static CSMoveReq GetRootAsCSMoveReq(ByteBuffer _bb, CSMoveReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CSMoveReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Rotation { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<B3.Protocol.CSMoveReq> CreateCSMoveReq(FlatBufferBuilder builder,
      float X = 0.0f,
      float Y = 0.0f,
      float Z = 0.0f,
      float Rotation = 0.0f) {
    builder.StartTable(4);
    CSMoveReq.AddRotation(builder, Rotation);
    CSMoveReq.AddZ(builder, Z);
    CSMoveReq.AddY(builder, Y);
    CSMoveReq.AddX(builder, X);
    return CSMoveReq.EndCSMoveReq(builder);
  }

  public static void StartCSMoveReq(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(0, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(1, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(2, z, 0.0f); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(3, rotation, 0.0f); }
  public static Offset<B3.Protocol.CSMoveReq> EndCSMoveReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<B3.Protocol.CSMoveReq>(o);
  }
}


static public class CSMoveReqVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Z*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Rotation*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
