// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CSPing : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_6(); }
  public static CSPing GetRootAsCSPing(ByteBuffer _bb) { return GetRootAsCSPing(_bb, new CSPing()); }
  public static CSPing GetRootAsCSPing(ByteBuffer _bb, CSPing obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CSPing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Tick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<B3.Protocol.CSPing> CreateCSPing(FlatBufferBuilder builder,
      long Tick = 0) {
    builder.StartTable(1);
    CSPing.AddTick(builder, Tick);
    return CSPing.EndCSPing(builder);
  }

  public static void StartCSPing(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTick(FlatBufferBuilder builder, long tick) { builder.AddLong(0, tick, 0); }
  public static Offset<B3.Protocol.CSPing> EndCSPing(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<B3.Protocol.CSPing>(o);
  }
}


static public class CSPingVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Tick*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
