// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

public enum EPacketProtocol : int
{
  CS_Ping = 1,
  SC_Pang = 2,
  CS_Pong = 3,
  SC_ErrorNotify = 100,
  ///////////////////////////////////////////////////////////////
  SC_UserInfoNotify = 10001,
  CS_MoveReq = 10011,
  SC_MoveRes = 10012,
  CS_JumpReq = 10013,
  SC_JumpRes = 10014,
  SC_LeaveNotify = 10031,
  CS_EmotionReq = 11001,
  SC_EmotionRes = 11002,
};


}
