// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SCLeaveNotify : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_6(); }
  public static SCLeaveNotify GetRootAsSCLeaveNotify(ByteBuffer _bb) { return GetRootAsSCLeaveNotify(_bb, new SCLeaveNotify()); }
  public static SCLeaveNotify GetRootAsSCLeaveNotify(ByteBuffer _bb, SCLeaveNotify obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SCLeaveNotify __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short UserID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<B3.Protocol.SCLeaveNotify> CreateSCLeaveNotify(FlatBufferBuilder builder,
      short UserID = 0) {
    builder.StartTable(1);
    SCLeaveNotify.AddUserID(builder, UserID);
    return SCLeaveNotify.EndSCLeaveNotify(builder);
  }

  public static void StartSCLeaveNotify(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUserID(FlatBufferBuilder builder, short userID) { builder.AddShort(0, userID, 0); }
  public static Offset<B3.Protocol.SCLeaveNotify> EndSCLeaveNotify(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<B3.Protocol.SCLeaveNotify>(o);
  }
}


static public class SCLeaveNotifyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UserID*/, 2 /*short*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
