// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SCPang : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_6(); }
  public static SCPang GetRootAsSCPang(ByteBuffer _bb) { return GetRootAsSCPang(_bb, new SCPang()); }
  public static SCPang GetRootAsSCPang(ByteBuffer _bb, SCPang obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SCPang __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Tick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ServerTick { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<B3.Protocol.SCPang> CreateSCPang(FlatBufferBuilder builder,
      long Tick = 0,
      long ServerTick = 0) {
    builder.StartTable(2);
    SCPang.AddServerTick(builder, ServerTick);
    SCPang.AddTick(builder, Tick);
    return SCPang.EndSCPang(builder);
  }

  public static void StartSCPang(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTick(FlatBufferBuilder builder, long tick) { builder.AddLong(0, tick, 0); }
  public static void AddServerTick(FlatBufferBuilder builder, long serverTick) { builder.AddLong(1, serverTick, 0); }
  public static Offset<B3.Protocol.SCPang> EndSCPang(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<B3.Protocol.SCPang>(o);
  }
}


static public class SCPangVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Tick*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*ServerTick*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
