// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace B3.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TUserInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_6(); }
  public static TUserInfo GetRootAsTUserInfo(ByteBuffer _bb) { return GetRootAsTUserInfo(_bb, new TUserInfo()); }
  public static TUserInfo GetRootAsTUserInfo(ByteBuffer _bb, TUserInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TUserInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int UserIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string UserName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUserNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUserNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<B3.Protocol.TUserInfo> CreateTUserInfo(FlatBufferBuilder builder,
      int UserIndex = 0,
      StringOffset UserNameOffset = default(StringOffset)) {
    builder.StartTable(2);
    TUserInfo.AddUserName(builder, UserNameOffset);
    TUserInfo.AddUserIndex(builder, UserIndex);
    return TUserInfo.EndTUserInfo(builder);
  }

  public static void StartTUserInfo(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUserIndex(FlatBufferBuilder builder, int userIndex) { builder.AddInt(0, userIndex, 0); }
  public static void AddUserName(FlatBufferBuilder builder, StringOffset userNameOffset) { builder.AddOffset(1, userNameOffset.Value, 0); }
  public static Offset<B3.Protocol.TUserInfo> EndTUserInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<B3.Protocol.TUserInfo>(o);
  }
}


static public class TUserInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UserIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*UserName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
